services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: supersecret
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data 
 
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
 
volumes:
  pgdata: